### ISSUE TITLE
This is not a map at all

### ISSUE THREAD

**Issue by erikdubbelboer** [gobs/sortedmap#1]
A map has the property that you can do O(1) lookups. Since this is implemented using a slice lookups are always much slower O(n).

**Comment by raff** [comment]
The package name may be misleading, but the README says "The sortedmap package provides some utility methods to sort maps by keys or values". It doesn't say anywhere this is an implementation of a sorted map, nor there are methods to use it as a map.

I will add some examples and better explanation. Thanks!
